# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c399d07a896e355d5a9e573e234be42fbb5c351d2484a8626323fc131c1ed765e7dac6dd930f4dfed866cf278cde36be591b9ac90a5b75e758f4f8429bd9db74

test:
  secret_key_base: 44d0982c51e8bcba44057cde7b5aeb06d232c698717e79f12fe53521442a0a712f77fdf01a1fe5e563149037ffac53709ef85958f25362f0ae38311dfbdad8e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
